version: 2.1
jobs:
  build_and_test:
    working_directory: ~/repo
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - run: npm install node
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - run: npm run
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: rebuild npm # modules need to be rebuilt to allow access
          command: npm rebuild
      - run:
          name: run tests
          command: sudo npm run test
workflows:
  build_and_test:
    jobs:
      - build_and_test